# Author: Fábio Madeira <fmadeira@ebi.ac.uk>, 2020
# test/run locally with
# gitlab-runner exec docker build_module
# gitlab-runner exec docker build_nodecli

# node 18.7
image: node:18.7-alpine3.16

before_script:
    # installing dependencies for node-canvas (https://github.com/Automattic/node-canvas)
    - apk add --no-cache build-base g++ cairo-dev pango-dev jpeg-dev giflib-dev librsvg-dev
    # installing project dependencies
    - npm install

stages:
    # building the ES modules and node CLI (also ES module now, from commonJS)
    - build

build_module:
    stage: build
    script: npm run build

build_nodecli:
    stage: build
    script: npm run build:cli
