site_name: Jdispatcher-viewers Documentation

theme:
  name: material
  locale: en
  highlightjs: true
  hljs_languages:
    - bash
    - typescript
    - javascript
    - html
    - css
  # favicon: docs/assets/images/favicon.ico
  # logo: docs/assets/images/jd_logo.png
  palette:
    primary: teal
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.top
#    - navigation.expand
#    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
    - Getting Started: 'index.md'
    - Demo: 'demo.md'
    - Web Components: 'webcomponents.md'
    - Script Embedding: 'script.md'
    - Developing a new visualisation:
      - Development: 'development.md'
    - API docs:
        - API: api/modules.html

plugins:
  - search

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.ebi.ac.uk/jdispatcher/
      name: Job Dispatcher
    - icon: fontawesome/solid/blog
      link: https://www.ebi.ac.uk/jdispatcher/blog/
      name: Blog
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ebi_jdispatcher
      name: Twitter
  analytics:
    provider: google
    property: G-VSNX2RKH87

docs_dir: docs/
repo_url: https://github.com/ebi-jdispatcher/jdispatcher-viewers
site_url: https://ebi-jdispatcher.github.io/jdispatcher-viewers/

# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/fabric.js/5.3.1/fabric.min.js

copyright: Copyright &copy; 2025 EMBL-EBI
