import svgToMiniDataURI from 'mini-svg-data-uri';
import { isBrowser, isNode } from 'browser-or-node';
import { VisualOutput } from './visual-output-app';
import { FunctionalPredictions } from './functional-predictions-app';
import {
  BasicCanvasRenderer,
  validateJobId,
  fetchData,
  dataAsType,
  getJdispatcherJsonURL,
  validateSubmittedJobIdInput,
  validateSubmittedDbfetchInput,
  getIPRMCDataModelFlatFromXML,
  countDecimals,
  ObjectCache,
  getDomainURLbyDatabase,
  domainDatabaseNameToString,
  getIPRMCDbfetchAccessions,
  getIPRMCDbfetchURL,
  getUniqueIPRMCDomainDatabases,
  numberToString,
  tooltipState,
} from './other-utilities';
import {
  DataModelEnum,
  ColorSchemeEnum,
  ScaleTypeEnum,
  ScoreTypeEnum,
  objectDefaults,
  lineDefaults,
  rectDefaults,
  textDefaults,
  toPositiveNumber,
  jobIdDefaults,
  JobIdValidable,
  ObjectType,
  TextType,
  RectType,
  ColorType,
  LineType,
  CoordsValues,
  RenderOptions,
  posnumber,
} from './custom-types';
import {
  SSSResultModel,
  IPRMCResultModel,
  IPRMCResultModelFlat,
  IprMatchFlat,
  IprMatchesFlat,
  Hsp,
  Hit,
} from './data-model';
import {
  HSVtoRGB,
  colorByDatabaseName,
  getRgbColorLogGradient,
  getRgbColorFixed,
  getRgbColorLinearGradient,
  getGradientSteps,
} from './color-utilities';
import {
  colorGenericGradient,
  colorNcbiBlastGradient,
  colorQualitativeGradient,
  qualitativeGradient,
  divergentGradient,
  getColorType,
  greyscaleGradient,
  heatmapGradient,
  ncbiBlastGradient,
  sequentialGradient,
} from './color-schemes';
import {
  drawCanvasWrapperStroke,
  drawColorSchemeCheckBoxText,
  drawContentDomainInfoText,
  drawContentFooterTextGroup,
  drawContentHeaderTextGroup,
  drawContentQuerySubjFooterTextGroup,
  drawContentSequenceInfoText,
  drawContentSupressText,
  drawContentTitleText,
  drawDomain,
  drawDomainCheckbox,
  drawDomainInfoTooltips,
  drawDomainLineTracks,
  drawDomainQueySubject,
  drawDomainTooltips,
  drawDomains,
  drawFooterLinkText,
  drawFooterText,
  drawHeaderLinkText,
  drawHeaderTextGroup,
  drawHitTransparentBox,
  drawHspNoticeText,
  drawLineAxis5Buckets,
  drawLineAxis6Buckets,
  drawLineTracks,
  drawLineTracksQuerySubject,
  drawNoHitsFoundText,
  drawProteinFeaturesText,
  drawScaleColorGradient,
  drawScaleLabelText,
  drawScaleScoreText,
  drawScaleTick4LabelsGroup,
  drawScaleTick5LabelsGroup,
  drawScaleTypeCheckBoxText,
  drawScoreText,
  drawScoreTypeCheckBoxText,
  drawURLInfoTooltip,
} from './drawing-utilities';

import {
  mouseClickDomain,
  mouseDownCheckbox,
  mouseDownDomainCheckbox,
  mouseDownLink,
  mouseOutCheckbox,
  mouseOutDomain,
  mouseOutDomainCheckbox,
  mouseOutText,
  mouseOverCheckbox,
  mouseOverDomain,
  mouseOverDomainCheckbox,
  mouseOverText,
} from './custom-events';

import {
  getDomainPixelCoords,
  getPixelCoords,
  getQuerySubjPixelCoords,
  getTextLegendPaddingFactor,
  getTotalPixels,
} from './coords-utilities';

// plugin support & module support
// if (typeof window === "undefined") {
if (isBrowser) {
  (window as any).VisualOutput = VisualOutput;
  (window as any).FunctionalPredictions = FunctionalPredictions;
  (window as any).validateJobId = validateJobId;
  (window as any).svgToMiniDataURI = svgToMiniDataURI;
  (window as any).fetchData = fetchData;
  (window as any).dataAsType = dataAsType;
  (window as any).getJdispatcherJsonURL = getJdispatcherJsonURL;
  (window as any).validateSubmittedJobIdInput = validateSubmittedJobIdInput;
  (window as any).validateSubmittedDbfetchInput = validateSubmittedDbfetchInput;
  (window as any).getIPRMCDataModelFlatFromXML = getIPRMCDataModelFlatFromXML;
  (window as any).ColorSchemeEnum = ColorSchemeEnum;
  (window as any).JDViewers = {
    VisualOutput: VisualOutput,
    FunctionalPredictions: FunctionalPredictions,
    BasicCanvasRenderer: BasicCanvasRenderer,
    validateJobId: validateJobId,
    svgToMiniDataURI: svgToMiniDataURI,
    fetchData: fetchData,
    dataAsType: dataAsType,
    getJdispatcherJsonURL: getJdispatcherJsonURL,
    validateSubmittedJobIdInput: validateSubmittedJobIdInput,
    validateSubmittedDbfetchInput: validateSubmittedDbfetchInput,
    getIPRMCDataModelFlatFromXML: getIPRMCDataModelFlatFromXML,
    countDecimals,
    ObjectCache,
    getDomainURLbyDatabase,
    domainDatabaseNameToString,
    getIPRMCDbfetchAccessions,
    getIPRMCDbfetchURL,
    getUniqueIPRMCDomainDatabases,
    numberToString,
    tooltipState,
    DataModelEnum,
    ColorSchemeEnum: ColorSchemeEnum,
    ScaleTypeEnum,
    ScoreTypeEnum,
    objectDefaults,
    lineDefaults,
    rectDefaults,
    textDefaults,
    toPositiveNumber,
    jobIdDefaults,
    JobIdValidable: {} as JobIdValidable,
    ObjectType: {} as ObjectType,
    TextType: {} as TextType,
    RectType: {} as RectType,
    ColorType: {} as ColorType,
    LineType: {} as LineType,
    CoordsValues: {} as CoordsValues,
    RenderOptions: {} as RenderOptions,
    posnumber: {} as posnumber,
    SSSResultModel: {} as SSSResultModel,
    IPRMCResultModel: {} as IPRMCResultModel,
    IPRMCResultModelFlat: {} as IPRMCResultModelFlat,
    IprMatchFlat: {} as IprMatchFlat,
    IprMatchesFlat: {} as IprMatchesFlat,
    Hsp: {} as Hsp,
    Hit: {} as Hit,
    HSVtoRGB,
    colorByDatabaseName,
    getRgbColorLogGradient,
    getRgbColorFixed,
    getRgbColorLinearGradient,
    getGradientSteps,
    colorGenericGradient,
    colorNcbiBlastGradient,
    colorQualitativeGradient,
    qualitativeGradient,
    divergentGradient,
    getColorType,
    greyscaleGradient,
    heatmapGradient,
    ncbiBlastGradient,
    sequentialGradient,
    drawCanvasWrapperStroke,
    drawColorSchemeCheckBoxText,
    drawContentDomainInfoText,
    drawContentFooterTextGroup,
    drawContentHeaderTextGroup,
    drawContentQuerySubjFooterTextGroup,
    drawContentSequenceInfoText,
    drawContentSupressText,
    drawContentTitleText,
    drawDomain,
    drawDomainCheckbox,
    drawDomainInfoTooltips,
    drawDomainLineTracks,
    drawDomainQueySubject,
    drawDomainTooltips,
    drawDomains,
    drawFooterLinkText,
    drawFooterText,
    drawHeaderLinkText,
    drawHeaderTextGroup,
    drawHitTransparentBox,
    drawHspNoticeText,
    drawLineAxis5Buckets,
    drawLineAxis6Buckets,
    drawLineTracks,
    drawLineTracksQuerySubject,
    drawNoHitsFoundText,
    drawProteinFeaturesText,
    drawScaleColorGradient,
    drawScaleLabelText,
    drawScaleScoreText,
    drawScaleTick4LabelsGroup,
    drawScaleTick5LabelsGroup,
    drawScaleTypeCheckBoxText,
    drawScoreText,
    drawScoreTypeCheckBoxText,
    drawURLInfoTooltip,
    mouseClickDomain,
    mouseDownCheckbox,
    mouseDownDomainCheckbox,
    mouseDownLink,
    mouseOutCheckbox,
    mouseOutDomain,
    mouseOutDomainCheckbox,
    mouseOutText,
    mouseOverCheckbox,
    mouseOverDomain,
    mouseOverDomainCheckbox,
    mouseOverText,
    getDomainPixelCoords,
    getPixelCoords,
    getQuerySubjPixelCoords,
    getTextLegendPaddingFactor,
    getTotalPixels,
  };
}
if (isNode) {
  module.exports = {
    VisualOutput: VisualOutput,
    FunctionalPredictions: FunctionalPredictions,
    validateJobId: validateJobId,
    svgToMiniDataURI: svgToMiniDataURI,
    fetchData: fetchData,
    dataAsType: dataAsType,
    getJdispatcherJsonURL: getJdispatcherJsonURL,
    validateSubmittedJobIdInput: validateSubmittedJobIdInput,
    validateSubmittedDbfetchInput: validateSubmittedDbfetchInput,
    getIPRMCDataModelFlatFromXML: getIPRMCDataModelFlatFromXML,
    ColorSchemeEnum: ColorSchemeEnum,
    JDViewers: {
      VisualOutput: VisualOutput,
      FunctionalPredictions: FunctionalPredictions,
      BasicCanvasRenderer: BasicCanvasRenderer,
      validateJobId: validateJobId,
      svgToMiniDataURI: svgToMiniDataURI,
      fetchData: fetchData,
      dataAsType: dataAsType,
      getJdispatcherJsonURL: getJdispatcherJsonURL,
      validateSubmittedJobIdInput: validateSubmittedJobIdInput,
      validateSubmittedDbfetchInput: validateSubmittedDbfetchInput,
      getIPRMCDataModelFlatFromXML: getIPRMCDataModelFlatFromXML,
      countDecimals,
      ObjectCache,
      getDomainURLbyDatabase,
      domainDatabaseNameToString,
      getIPRMCDbfetchAccessions,
      getIPRMCDbfetchURL,
      getUniqueIPRMCDomainDatabases,
      numberToString,
      tooltipState,
      DataModelEnum,
      ColorSchemeEnum: ColorSchemeEnum,
      ScaleTypeEnum,
      ScoreTypeEnum,
      objectDefaults,
      lineDefaults,
      rectDefaults,
      textDefaults,
      toPositiveNumber,
      jobIdDefaults,
      JobIdValidable: {} as JobIdValidable,
      ObjectType: {} as ObjectType,
      TextType: {} as TextType,
      RectType: {} as RectType,
      ColorType: {} as ColorType,
      LineType: {} as LineType,
      CoordsValues: {} as CoordsValues,
      RenderOptions: {} as RenderOptions,
      posnumber: {} as posnumber,
      SSSResultModel: {} as SSSResultModel,
      IPRMCResultModel: {} as IPRMCResultModel,
      IPRMCResultModelFlat: {} as IPRMCResultModelFlat,
      IprMatchFlat: {} as IprMatchFlat,
      IprMatchesFlat: {} as IprMatchesFlat,
      Hsp: {} as Hsp,
      Hit: {} as Hit,
      HSVtoRGB,
      colorByDatabaseName,
      getRgbColorLogGradient,
      getRgbColorFixed,
      getRgbColorLinearGradient,
      getGradientSteps,
      colorGenericGradient,
      colorNcbiBlastGradient,
      colorQualitativeGradient,
      qualitativeGradient,
      divergentGradient,
      getColorType,
      greyscaleGradient,
      heatmapGradient,
      ncbiBlastGradient,
      sequentialGradient,
      drawCanvasWrapperStroke,
      drawColorSchemeCheckBoxText,
      drawContentDomainInfoText,
      drawContentFooterTextGroup,
      drawContentHeaderTextGroup,
      drawContentQuerySubjFooterTextGroup,
      drawContentSequenceInfoText,
      drawContentSupressText,
      drawContentTitleText,
      drawDomain,
      drawDomainCheckbox,
      drawDomainInfoTooltips,
      drawDomainLineTracks,
      drawDomainQueySubject,
      drawDomainTooltips,
      drawDomains,
      drawFooterLinkText,
      drawFooterText,
      drawHeaderLinkText,
      drawHeaderTextGroup,
      drawHitTransparentBox,
      drawHspNoticeText,
      drawLineAxis5Buckets,
      drawLineAxis6Buckets,
      drawLineTracks,
      drawLineTracksQuerySubject,
      drawNoHitsFoundText,
      drawProteinFeaturesText,
      drawScaleColorGradient,
      drawScaleLabelText,
      drawScaleScoreText,
      drawScaleTick4LabelsGroup,
      drawScaleTick5LabelsGroup,
      drawScaleTypeCheckBoxText,
      drawScoreText,
      drawScoreTypeCheckBoxText,
      drawURLInfoTooltip,
      mouseClickDomain,
      mouseDownCheckbox,
      mouseDownDomainCheckbox,
      mouseDownLink,
      mouseOutCheckbox,
      mouseOutDomain,
      mouseOutDomainCheckbox,
      mouseOutText,
      mouseOverCheckbox,
      mouseOverDomain,
      mouseOverDomainCheckbox,
      mouseOverText,
      getDomainPixelCoords,
      getPixelCoords,
      getQuerySubjPixelCoords,
      getTextLegendPaddingFactor,
      getTotalPixels,
    },
  };
}

// web-component support
import './visual-output-webcomponent';
import './functional-predictions-webcomponent';

// demo index page with JobId input form (implemented in TypeScript)
import './demo';
