name: jdispatcher-viewers
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # Check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      #----------------------------------------------
      # Install Canvas/Fabric dependencies
      #----------------------------------------------
      - name: Install Canvas/Fabric Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential \
            g++ libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      #----------------------------------------------
      # Try a "clean" install (without forcing dependencies)
      #----------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20'
      - name: Clean install
        run: npm install --dry-run
      #----------------------------------------------
      # Check if lock-file is compatible with packages.json
      #----------------------------------------------
      - name: Check lockfile
        run: |
          npm install --force
          git ls-files -m | grep -q package-lock.json \
            && { echo "WARNING - Lock file is outdated!" && exit 1; }
          exit 0
      #----------------------------------------------
      # Run npm audit
      #----------------------------------------------
      - name: Npm audit
        run: npm audit
      #----------------------------------------------
      # Check code format
      #----------------------------------------------
      - name: Check code format
        run: npm run format
      #----------------------------------------------
      # Run tests with Jest
      #----------------------------------------------
      - name: Run tests with Jest
        run: npm test
      #----------------------------------------------
      # Build Module
      #----------------------------------------------
      - name: Build module
        run: npm run build
      #----------------------------------------------
      # Build Node CLI
      #----------------------------------------------
      - name: Build CLI
        run: npm run build:cli
